# # create a workflow to build and deploy your Vue app to GitHub Pages
name: develop

on:
  push:
    branches: ["main"]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    environment: develop
    name: Hello World
    steps:
      - uses: actions/checkout@v3
      - uses : actions/setup-node@v3
        with:
          node-version: 18
      - run: npm config set -- //gitlab.com/api/v4/packages/npm/:_authToken=${{ vars.GL_TOKEN }}
      - run: npm config set @playvox:registry https://gitlab.com/api/v4/packages/npm/
      - run: npm ci
      - run: npm run lint
      - run: npm run test:unit


# name: Build Vue
# on:
#   push:
#     branches: ["main"]
# jobs:
#   build_vue:
#     runs-on: ubuntu-latest
#     name: Build Vue
#     steps:
#       - uses: actions/checkout@v2
#       - name: print
#         run: echo "Hola mundo !!! $CI_NAME_TEST"
#       - id: Build-Vue
#         uses: xRealNeon/VuePagesAction@1.0.1
#         with:
#           username: "juannn91"
#           reponame: "portfolio-spa-page"
#           token: ${{ secrets.GITHUB_TOKEN }}
